name: Merge Branches
description: Propose merging changes from one branch into another.
title: "🔀 Merge [source_branch] into [target_branch]"
labels: ["merge"]
projects: ["algosup/2024-2025-project-3-quickest-path-team-7"]
assignees:
  - Pierre2103
  - HiNett
body:
  - type: markdown
    attributes:
      value: |
         🔀 **Thank you for initiating a merge!**  
         Merging branches is a critical step in ensuring the codebase stays clean and functional. Please provide the necessary details below.  
         ⚠️ **Remember:** Ensure all tests pass and conflicts are resolved before proceeding.
  - type: input
    id: date
    attributes:
      label: 📅 Merge Date
      description: Specify the date when this merge is being proposed.
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
  - type: textarea
    id: merge-purpose
    attributes:
      label: 📝 Merge Purpose
      description: What is the purpose of this merge? Is it to finalize a feature, resolve a conflict, or integrate updates?
      placeholder: "Explain why this merge is necessary."
    validations:
      required: true
  - type: textarea
    id: branch-changes
    attributes:
      label: 🔄 Branch Changes
      description: Summarize the key changes introduced in the branch being merged.
      placeholder: e.g., "1. Added X. 2. Updated Y. 3. Fixed Z."
    validations:
      required: true
  - type: textarea
    id: merge-risks
    attributes:
      label: ⚠️ Potential Merge Risks
      description: Identify any risks, such as conflicts or regressions, that might arise from this merge.
      placeholder: e.g., "Risk of conflicts in file A, regression in feature B."
    validations:
      required: false
  - type: checkboxes
    id: merge-checklist
    attributes:
      label: ✅ Merge Checklist
      description: Verify that the following steps are completed before proceeding with the merge.
      options:
        - label: 🟢 Code conflicts have been resolved
          required: true
        - label: 👀 Code was reviewed and approved by peers
          required: true
        - label: ✅ All tests pass without errors
          required: true
        - label: 📚 Documentation is updated, if applicable
          required: false