name: Typography Report
description: Report a typography error in project documents.
title: "✏️ [Typography]: "
labels: ["documentation", "typography"]
projects: ["algosup/2024-2025-project-3-quickest-path-team-7"]
assignees:
  - Pierre2103
  - HiNett
body:
  - type: markdown
    attributes:
      value: |
        📝 **Thank you for reporting a typography issue!**  
        Clear and detailed reports help us maintain high-quality project documentation. Please fill in the form below.
  - type: input
    id: date
    attributes:
      label: 📅 Report Date
      description: Specify the date when this issue was reported.
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
  - type: dropdown
    id: document-type
    attributes:
      label: 📄 Document Type
      description: Which document contains the typo?
      options:
        - Functional Specification
        - Technical Specification
        - Test Plan
        - User Manual
        - Other
    validations:
      required: true
  - type: input
    id: document-type-other
    attributes:
      label: 🆕 Other Document Type
      description: If "Other," please specify the document type.
      placeholder: Enter the document type.
    validations:
      required: false
  - type: dropdown
    id: document-author
    attributes:
      label: ✍️ Document Author
      description: Who wrote the document?
      options:
        - Elone DELILLE
        - Abderrazaq MAKRAN
        - Guillaume DERAMCHI
        - Pierre GORIN
        - Benoît DE KEYN
        - Axel DAVID
        - Tino GABET
    validations:
      required: true
  - type: textarea
    id: typo-location
    attributes:
      label: 📌 Typo Location
      description: Where exactly is the typo? (Line, section, or paragraph)
      placeholder: Provide precise details.
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: ❌ Error Description
      description: What is the typo?
      placeholder: Describe the error.
    validations:
      required: true
  - type: textarea
    id: correction
    attributes:
      label: ✅ Suggested Correction
      description: What is the suggested correction?
      placeholder: Provide the corrected text.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: ℹ️ Additional Information
      description: Add any additional details or context that might help us address the issue.
      placeholder: Additional details here.
    validations:
      required: false
