name: Continuous Testing

on:
  push:
    branches:
      - main
      - dev
      - qa
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Fetch Google Test submodule

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run unit tests
      run: cd build && ctest --output-on-failure